// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdjVTITihD1N9yu4LWwS0EtIC1nlFrD_Y',
    appId: '1:138118282421:web:2dba489875c013840c52fc',
    messagingSenderId: '138118282421',
    projectId: 'fir-app-web-a839e',
    authDomain: 'fir-app-web-a839e.firebaseapp.com',
    storageBucket: 'fir-app-web-a839e.appspot.com',
    measurementId: 'G-0JYDCSKD5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5rHMOw13I-fJgc0NCUAtjAt1His8OPe4',
    appId: '1:138118282421:android:146996e72636796d0c52fc',
    messagingSenderId: '138118282421',
    projectId: 'fir-app-web-a839e',
    storageBucket: 'fir-app-web-a839e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4kIh6vw3i_1hfW74l3fG5F-8frrrtPlI',
    appId: '1:138118282421:ios:09fd221bafc6d8f60c52fc',
    messagingSenderId: '138118282421',
    projectId: 'fir-app-web-a839e',
    storageBucket: 'fir-app-web-a839e.appspot.com',
    iosClientId: '138118282421-kdrcqspqojhd1k2c7lo825dev8rifnh6.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAppWeb',
  );
}
